# Generated by Django 5.2.8 on 2025-11-09 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainTumorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri_image', models.ImageField(help_text='Uploaded MRI scan', upload_to='uploads/mri_scans/')),
                ('masked_image', models.ImageField(blank=True, help_text='Generated segmentation mask', null=True, upload_to='uploads/masked_results/')),
                ('prediction_label', models.CharField(blank=True, help_text='Result (Tumor / No Tumor)', max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0-1)', null=True)),
                ('detected_region', models.TextField(blank=True, help_text='Optional details like bounding boxes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bt_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
