# Generated by Django 5.2.8 on 2025-11-08 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField(help_text='Glucose level in mg/dL')),
                ('blood_pressure_systolic', models.FloatField(help_text='Systolic blood pressure (mm Hg)')),
                ('blood_pressure_diastolic', models.FloatField(help_text='Diastolic blood pressure (mm Hg)')),
                ('skin_thickness', models.FloatField(help_text='Skin thickness (mm)')),
                ('insulin', models.FloatField(help_text='Insulin level (μU/mL)')),
                ('bmi', models.FloatField(help_text='Body Mass Index (kg/m²)')),
                ('age', models.IntegerField(help_text='Age in years')),
                ('pregnancies', models.IntegerField(help_text='Number of pregnancies')),
                ('diabetes_pedigree_function', models.FloatField(help_text='Diabetes pedigree function')),
                ('prediction_result', models.CharField(blank=True, help_text='Predicted outcome (e.g., Diabetic / Non-diabetic)', max_length=50, null=True)),
                ('prediction_probability', models.FloatField(blank=True, help_text='Prediction probability (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
