# Generated by Django 5.2.8 on 2025-11-09 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainTumorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri_image', models.ImageField(help_text='Upload MRI image', upload_to='uploads/mri_scans/')),
                ('prediction_label', models.CharField(blank=True, help_text='Predicted result (e.g., Tumor / No Tumor)', max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence (0–1)', null=True)),
                ('detected_region', models.TextField(blank=True, help_text='Region of interest or detected tumor coordinates (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brain_tumor_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
